; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "»ðÑæ¼ì²â"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "WhiteSheep"
!define PRODUCT_WEB_SITE "https://github.com/Ekkosun/Firedetection"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Demo.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\Demo.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\»ðÑæ¼ì²â"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "D:\ProgramDemo\Demo\excuteable\Demo.exe"
  CreateDirectory "$SMPROGRAMS\»ðÑæ¼ì²â"
  CreateShortCut "$SMPROGRAMS\»ðÑæ¼ì²â\»ðÑæ¼ì²â.lnk" "$INSTDIR\Demo.exe"
  CreateShortCut "$DESKTOP\»ðÑæ¼ì²â.lnk" "$INSTDIR\Demo.exe"
  SetOutPath "$INSTDIR\bearer"
  SetOverwrite try
  File "D:\ProgramDemo\Demo\excuteable\bearer\qgenericbearer.dll"
  SetOutPath "$INSTDIR"
  File "D:\ProgramDemo\Demo\excuteable\D3Dcompiler_47.dll"
  SetOutPath "$INSTDIR\iconengines"
  File "D:\ProgramDemo\Demo\excuteable\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qgif.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qicns.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qico.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qjpeg.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qsvg.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qtga.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qtiff.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qwbmp.dll"
  File "D:\ProgramDemo\Demo\excuteable\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR"
  File "D:\ProgramDemo\Demo\excuteable\libEGL.dll"
  File "D:\ProgramDemo\Demo\excuteable\libgcc_s_seh-1.dll"
  File "D:\ProgramDemo\Demo\excuteable\libGLESv2.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_core410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_dnn410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_highgui410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_imgcodecs410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_imgproc410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libopencv_video410.dll"
  File "D:\ProgramDemo\Demo\excuteable\libstdc++-6.dll"
  File "D:\ProgramDemo\Demo\excuteable\libwinpthread-1.dll"
  File "D:\ProgramDemo\Demo\excuteable\opengl32sw.dll"
  File "D:\ProgramDemo\Demo\excuteable\yolov3-tiny.backup"
  File "D:\ProgramDemo\Demo\excuteable\yolov3-tiny.cfg"
  SetOutPath "$INSTDIR\platforms"
  File "D:\ProgramDemo\Demo\excuteable\platforms\qwindows.dll"
  SetOutPath "$INSTDIR"
  File "D:\ProgramDemo\Demo\excuteable\Qt5Core.dll"
  File "D:\ProgramDemo\Demo\excuteable\Qt5Gui.dll"
  File "D:\ProgramDemo\Demo\excuteable\Qt5Network.dll"
  File "D:\ProgramDemo\Demo\excuteable\Qt5Svg.dll"
  File "D:\ProgramDemo\Demo\excuteable\Qt5Widgets.dll"
  SetOutPath "$INSTDIR\styles"
  File "D:\ProgramDemo\Demo\excuteable\styles\qwindowsvistastyle.dll"
  SetOutPath "$INSTDIR\translations"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_ar.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_bg.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_ca.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_cs.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_da.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_de.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_en.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_es.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_fi.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_fr.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_gd.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_he.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_hu.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_it.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_ja.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_ko.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_lv.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_pl.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_ru.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_sk.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_tr.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_uk.qm"
  File "D:\ProgramDemo\Demo\excuteable\translations\qt_zh_TW.qm"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\»ðÑæ¼ì²â\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\»ðÑæ¼ì²â\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Demo.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\Demo.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) ÒÑ³É¹¦µØ´ÓÄãµÄ¼ÆËã»úÒÆ³ý¡£"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "ÄãÈ·ÊµÒªÍêÈ«ÒÆ³ý $(^Name) £¬Æä¼°ËùÓÐµÄ×é¼þ£¿" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\translations\qt_zh_TW.qm"
  Delete "$INSTDIR\translations\qt_uk.qm"
  Delete "$INSTDIR\translations\qt_tr.qm"
  Delete "$INSTDIR\translations\qt_sk.qm"
  Delete "$INSTDIR\translations\qt_ru.qm"
  Delete "$INSTDIR\translations\qt_pl.qm"
  Delete "$INSTDIR\translations\qt_lv.qm"
  Delete "$INSTDIR\translations\qt_ko.qm"
  Delete "$INSTDIR\translations\qt_ja.qm"
  Delete "$INSTDIR\translations\qt_it.qm"
  Delete "$INSTDIR\translations\qt_hu.qm"
  Delete "$INSTDIR\translations\qt_he.qm"
  Delete "$INSTDIR\translations\qt_gd.qm"
  Delete "$INSTDIR\translations\qt_fr.qm"
  Delete "$INSTDIR\translations\qt_fi.qm"
  Delete "$INSTDIR\translations\qt_es.qm"
  Delete "$INSTDIR\translations\qt_en.qm"
  Delete "$INSTDIR\translations\qt_de.qm"
  Delete "$INSTDIR\translations\qt_da.qm"
  Delete "$INSTDIR\translations\qt_cs.qm"
  Delete "$INSTDIR\translations\qt_ca.qm"
  Delete "$INSTDIR\translations\qt_bg.qm"
  Delete "$INSTDIR\translations\qt_ar.qm"
  Delete "$INSTDIR\styles\qwindowsvistastyle.dll"
  Delete "$INSTDIR\Qt5Widgets.dll"
  Delete "$INSTDIR\Qt5Svg.dll"
  Delete "$INSTDIR\Qt5Network.dll"
  Delete "$INSTDIR\Qt5Gui.dll"
  Delete "$INSTDIR\Qt5Core.dll"
  Delete "$INSTDIR\platforms\qwindows.dll"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\libwinpthread-1.dll"
  Delete "$INSTDIR\libstdc++-6.dll"
  Delete "$INSTDIR\libopencv_video410.dll"
  Delete "$INSTDIR\libopencv_imgproc410.dll"
  Delete "$INSTDIR\libopencv_imgcodecs410.dll"
  Delete "$INSTDIR\libopencv_highgui410.dll"
  Delete "$INSTDIR\libopencv_dnn410.dll"
  Delete "$INSTDIR\libopencv_core410.dll"
  Delete "$INSTDIR\libGLESv2.dll"
  Delete "$INSTDIR\libgcc_s_seh-1.dll"
  Delete "$INSTDIR\libEGL.dll"
  Delete "$INSTDIR\imageformats\qwebp.dll"
  Delete "$INSTDIR\imageformats\qwbmp.dll"
  Delete "$INSTDIR\imageformats\qtiff.dll"
  Delete "$INSTDIR\imageformats\qtga.dll"
  Delete "$INSTDIR\imageformats\qsvg.dll"
  Delete "$INSTDIR\imageformats\qjpeg.dll"
  Delete "$INSTDIR\imageformats\qico.dll"
  Delete "$INSTDIR\imageformats\qicns.dll"
  Delete "$INSTDIR\imageformats\qgif.dll"
  Delete "$INSTDIR\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\D3Dcompiler_47.dll"
  Delete "$INSTDIR\bearer\qgenericbearer.dll"
  Delete "$INSTDIR\Demo.exe"
  Delete "$INSTDIR\yolov3-tiny.backup"
  Delete "$INSTDIR\yolov3-tiny.cfg"
  Delete "$INSTDIR\*.mp4"
  Delete "$SMPROGRAMS\»ðÑæ¼ì²â\Uninstall.lnk"
  Delete "$SMPROGRAMS\»ðÑæ¼ì²â\Website.lnk"
  Delete "$DESKTOP\»ðÑæ¼ì²â.lnk"
  Delete "$SMPROGRAMS\»ðÑæ¼ì²â\»ðÑæ¼ì²â.lnk"

  RMDir "$SMPROGRAMS\»ðÑæ¼ì²â"
  RMDir "$INSTDIR\translations"
  RMDir "$INSTDIR\styles"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR\bearer"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd